services:
  - type: web
    name: spotify-top-1000
    env: python
    plan: free
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app:api --host 0.0.0.0 --port $PORT"
